# Generated by Django 4.2.4 on 2024-06-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Age',
            field=models.IntegerField(max_length=10),
        ),
    ]
