# Generated by Django 4.2.4 on 2024-06-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Age',
            field=models.CharField(max_length=10),
        ),
    ]
