# Generated by Django 4.2.4 on 2024-06-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Age',
        ),
    ]
